<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZctH0Dx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZctH0Dx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZctH0Dx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZctH0Dx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZctH0Dx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZctH0Dx',
    'container.build_id' => '5d240320',
    'container.build_time' => 1590068036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZctH0Dx');
